### ISSUE TITLE
Session serializers page mentions Gson class that doesn't exist

### ISSUE THREAD

**Issue by rnikander** [ktorio/ktorio.github.io#167]
Maybe I'm just failing to find it? I don't see `GsonSessionSerializer` anywhere. The one mentioned right before (`SessionSerializerReflection`) does exist in the main github repo. 

https://ktor.io/servers/features/sessions/serializers.html#GsonSessionSerializer

**Comment by cy6erGn0m** [comment]
It's implementation is mentioned at the same page above. But making such section is quite confusing since GsonSessionSerializer is not provided out of the box. The reason why it is not provided is that json is relatively large so sending a json-serialized session with cookies for every request would generate a lot of traffic. This is the default serializer is so weird.
