### ISSUE TITLE
Sidebar oveflow

### ISSUE THREAD

**Issue by IRus** [ktorio/ktorio.github.io#79]
![screenshot from 2018-09-21 17-16-28](https://user-images.githubusercontent.com/493656/45887221-d6834680-bdc3-11e8-938b-0f691bb4d475.png)

Ref in theme: https://github.com/xriley/PrettyDocs-Theme/issues/12

I'm working on this issue.

**Comment by IRus** [comment]
Reproduced in:

Name 	Firefox
Version 	62.0
Build ID 	20180913170256

Name 	Firefox
Version 	63.0a1
Build ID 	20180814184653

Google Chrome
Version 69.0.3497.100 (Official Build) (64-bit)

Safari on Ipad 2018, iOS 12

**Comment by soywiz** [comment]
It was fixed here:
* https://github.com/ktorio/ktorio.github.io/pull/76
And here:
* https://github.com/ktorio/ktorio.github.io/pull/77

The problem was that I reverted the first PR and when merging the second one, that commit already existed so had to manually revert the revert.

Please, check that already works for you and close if it is the case.

Thanks for the report!

**Comment by IRus** [comment]
Works in all browsers mentioned before.
